[package]
name = "messager"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "Messager"
readme = "README.md"
homepage = "https://github.com/Azleal/messager"
documentation = "https://github.com/Azleal/messager"
repository = "https://github.com/Azleal/messager"

[dependencies]
